site_name: My First Awesome DaC Site
site_description: A site build with Material for MKDocs
site_url: https://leonardopangaio.github.io/MKDocs/

theme:
  name: material
  custom_dir: overrides
  language: pt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: yellow

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leonardopangaio
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/leonardo-pangaio
  analytics:
    provider: google
    property: G-0XMGLZ0BX9
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept

copyright: Copyright &copy; 2024 - 2025 Leonardo Pangaio

plugins: 
  - search
  
  - blog:
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_allowed:
        - Tech
        - Life
      post_url_format: "{slug}"
  
  - tags:
      tags_file: tags.md
  
  # Needs to be restarted manually
  # http://127.0.0.1:8000/MKDocs/feed_rss_created.xml
  # http://127.0.0.1:8000/MKDocs/feed_rss_updated.xml
  - rss:
      match_path: blog/posts/.* 
      enable: true
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags
  
  - git-committers:
      enabled: true
      repository: leonardopangaio/MKDocs
      branch: main
      docs_path: docs/blog/
      exclude:
        - docs/glossary/*
      token: !ENV GH_TOKEN
  
  # The language must be only pt, not pt-BR
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true