site_name: My First DaC
site_url: https://leonardopangaio.github.io/MKDocs/
theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: yellow
extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leonardopangaio
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/leonardo-pangaio
copyright: Copyright &copy; 2024 - 2025 Leonardo Pangaio